--liquibase formatted sql
--changeset microgram:001
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    avatar VARCHAR(255) NOT NULL,
    information VARCHAR(1000)
);
CREATE TABLE publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    image VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES users(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT uq_subscription UNIQUE (subscriber_id, author_id),
    CONSTRAINT different_users CHECK (subscriber_id <> author_id)
);
CREATE TABLE publication_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id BIGINT NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_publication_like UNIQUE (publication_id, user_id)
);
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id BIGINT NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_publications_user ON publications(user_id);
CREATE INDEX idx_subscriptions_author ON subscriptions(author_id);
CREATE INDEX idx_comments_publication ON comments(publication_id);
